name: 'ci'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kpenfound/multiplatform-action@v0.1.0
        with:
          script: main.py
